# Question 1

## (A)

In [1]:
## Import necessary packages

from cvxopt import solvers
import numpy as np
from cvxopt import matrix
import pprint

In [2]:
c = np.matrix([[3,4.5,2.5,1,2,4]]) 

print(matrix(c))

[ 3.00e+00  4.50e+00  2.50e+00  1.00e+00  2.00e+00  4.00e+00]



In [3]:
A = np.matrix([[1,0,0,1,0,0],
            [-2,0,0,0,-1,0],
            [2,0,0,0,0,1],
            [0,-1,0,-2,0,0],
            [0,2,0,0,2,0],
            [0,2.5,0,0,0,2],
            [0,0,-1.5,-1,0,0],
            [0,0,-1.5,0,-1,0],
            [0,0,2.5,0,0,1],
            [-1,0,0,0,0,0],
            [0,-1,0,0,0,0],
            [0,0,-1,0,0,0],
            [0,0,0,-1,0,0],
            [0,0,0,0,-1,0],
            [0,0,0,0,0,-1]])
#Coefficient matrix for the constraints, enter column by column
print(matrix(A))

[ 1.00e+00  0.00e+00  0.00e+00  1.00e+00  0.00e+00  0.00e+00]
[-2.00e+00  0.00e+00  0.00e+00  0.00e+00 -1.00e+00  0.00e+00]
[ 2.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  1.00e+00]
[ 0.00e+00 -1.00e+00  0.00e+00 -2.00e+00  0.00e+00  0.00e+00]
[ 0.00e+00  2.00e+00  0.00e+00  0.00e+00  2.00e+00  0.00e+00]
[ 0.00e+00  2.50e+00  0.00e+00  0.00e+00  0.00e+00  2.00e+00]
[ 0.00e+00  0.00e+00 -1.50e+00 -1.00e+00  0.00e+00  0.00e+00]
[ 0.00e+00  0.00e+00 -1.50e+00  0.00e+00 -1.00e+00  0.00e+00]
[ 0.00e+00  0.00e+00  2.50e+00  0.00e+00  0.00e+00  1.00e+00]
[-1.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
[ 0.00e+00 -1.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
[ 0.00e+00  0.00e+00 -1.00e+00  0.00e+00  0.00e+00  0.00e+00]
[ 0.00e+00  0.00e+00  0.00e+00 -1.00e+00  0.00e+00  0.00e+00]
[ 0.00e+00  0.00e+00  0.00e+00  0.00e+00 -1.00e+00  0.00e+00]
[ 0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00 -1.00e+00]



In [6]:
b = np.matrix([[10],
               [-7],
               [10],
               [-7],
               [7],
               [10],
               [-7],
               [-7],
               [10],
               [0],
               [0],
               [0],
               [0],
               [0],
               [0]])
print(matrix(b))

[ 10]
[ -7]
[ 10]
[ -7]
[  7]
[ 10]
[ -7]
[ -7]
[ 10]
[  0]
[  0]
[  0]
[  0]
[  0]
[  0]



In [8]:
sol = solvers.lp(matrix(c.transpose(),tc = 'd'), matrix(A,tc='d'), matrix(b,tc='d')) 

## -ct is the coefficient of objective function. 
## A is the constraint matrix
## b is the right-hand-side of the constraints

#Print the solution
print (sol['x']) 


     pcost       dcost       gap    pres   dres   k/t
 0:  4.0809e+01 -6.9174e-02  1e+02  4e-01  2e+00  1e+00
 1:  1.3734e+01 -1.4670e+01  1e+02  3e-01  1e+00  4e+00
 2:  2.1167e+01  1.6553e+01  2e+01  5e-02  2e-01  2e+00
 3:  2.1402e+01  2.0493e+01  3e+00  1e-02  4e-02  3e-01
 4:  2.1584e+01  2.1569e+01  5e-02  2e-04  7e-04  4e-03
 5:  2.1583e+01  2.1583e+01  5e-04  2e-06  7e-06  4e-05
 6:  2.1583e+01  2.1583e+01  5e-06  2e-08  7e-08  4e-07
Optimal solution found.
[ 1.75e+00]
[-4.93e-08]
[ 2.33e+00]
[ 3.50e+00]
[ 3.50e+00]
[-6.91e-08]



## (C)

In [9]:
c = np.matrix([[2,1,3,3,2,0]]) 

print(matrix(c))

[ 2  1  3  3  2  0]



In [10]:
A = np.matrix([[1,0,0,1,0,0],
            [-2,0,0,0,-1,0],
            [2,0,0,0,0,1],
            [0,-1,0,-2,0,0],
            [0,2,0,0,2,0],
            [0,2.5,0,0,0,2],
            [0,0,-1.5,-1,0,0],
            [0,0,-1.5,0,-1,0],
            [0,0,2.5,0,0,1],
            [-1,0,0,0,0,0],
            [0,-1,0,0,0,0],
            [0,0,-1,0,0,0],
            [0,0,0,-1,0,0],
            [0,0,0,0,-1,0],
            [0,0,0,0,0,-1]])
#Coefficient matrix for the constraints, enter column by column
print(matrix(A))

[ 1.00e+00  0.00e+00  0.00e+00  1.00e+00  0.00e+00  0.00e+00]
[-2.00e+00  0.00e+00  0.00e+00  0.00e+00 -1.00e+00  0.00e+00]
[ 2.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  1.00e+00]
[ 0.00e+00 -1.00e+00  0.00e+00 -2.00e+00  0.00e+00  0.00e+00]
[ 0.00e+00  2.00e+00  0.00e+00  0.00e+00  2.00e+00  0.00e+00]
[ 0.00e+00  2.50e+00  0.00e+00  0.00e+00  0.00e+00  2.00e+00]
[ 0.00e+00  0.00e+00 -1.50e+00 -1.00e+00  0.00e+00  0.00e+00]
[ 0.00e+00  0.00e+00 -1.50e+00  0.00e+00 -1.00e+00  0.00e+00]
[ 0.00e+00  0.00e+00  2.50e+00  0.00e+00  0.00e+00  1.00e+00]
[-1.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
[ 0.00e+00 -1.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
[ 0.00e+00  0.00e+00 -1.00e+00  0.00e+00  0.00e+00  0.00e+00]
[ 0.00e+00  0.00e+00  0.00e+00 -1.00e+00  0.00e+00  0.00e+00]
[ 0.00e+00  0.00e+00  0.00e+00  0.00e+00 -1.00e+00  0.00e+00]
[ 0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00 -1.00e+00]



In [11]:
b = np.matrix([[10],
               [-7],
               [10],
               [-7],
               [7],
               [10],
               [-7],
               [-7],
               [10],
               [0],
               [0],
               [0],
               [0],
               [0],
               [0]])
print(matrix(b))

[ 10]
[ -7]
[ 10]
[ -7]
[  7]
[ 10]
[ -7]
[ -7]
[ 10]
[  0]
[  0]
[  0]
[  0]
[  0]
[  0]



In [12]:
sol = solvers.lp(matrix(-c.transpose(),tc = 'd'), matrix(A,tc='d'), matrix(b,tc='d')) 

## -ct is the coefficient of objective function. 
## A is the constraint matrix
## b is the right-hand-side of the constraints

#Print the solution
print (sol['x']) 

     pcost       dcost       gap    pres   dres   k/t
 0: -2.8341e+01 -6.1184e+01  9e+01  4e-01  2e+00  1e+00
 1: -4.2195e+01 -4.9566e+01  2e+01  9e-02  4e-01  1e+00
 2: -4.4102e+01 -4.6500e+01  8e+00  3e-02  1e-01  5e-01
 3: -4.6774e+01 -4.7385e+01  2e+00  8e-03  4e-02  1e-01
 4: -4.7244e+01 -4.7253e+01  3e-02  1e-04  6e-04  2e-03
 5: -4.7250e+01 -4.7250e+01  3e-04  1e-06  6e-06  2e-05
 6: -4.7250e+01 -4.7250e+01  3e-06  1e-08  6e-08  2e-07
Optimal solution found.
[ 1.75e+00]
[ 7.96e-08]
[ 4.00e+00]
[ 8.25e+00]
[ 3.50e+00]
[ 1.26e-07]



## (B)

In [13]:
a = 0.7
c = np.matrix([[5*a-3,5.5*a - 4.5,5.5*a - 2.5,4*a-1,4*a-2,4*a-4]]) 

print(matrix(c))

[ 5.00e-01 -6.50e-01  1.35e+00  1.80e+00  8.00e-01 -1.20e+00]



In [14]:
sol = solvers.lp(matrix(-c.transpose(),tc = 'd'), matrix(A,tc='d'), matrix(b,tc='d')) 

## -ct is the coefficient of objective function. 
## A is the constraint matrix
## b is the right-hand-side of the constraints

#Print the solution
print (sol['x']) 

     pcost       dcost       gap    pres   dres   k/t
 0: -7.5957e+00 -3.6125e+01  8e+01  4e-01  3e+00  1e+00
 1: -1.8972e+01 -2.4941e+01  2e+01  9e-02  7e-01  1e+00
 2: -2.2926e+01 -2.4810e+01  8e+00  3e-02  2e-01  6e-01
 3: -2.3867e+01 -2.3974e+01  4e-01  2e-03  1e-02  3e-02
 4: -2.3924e+01 -2.3926e+01  4e-03  2e-05  1e-04  3e-04
 5: -2.3925e+01 -2.3925e+01  4e-05  2e-07  1e-06  3e-06
 6: -2.3925e+01 -2.3925e+01  4e-07  2e-09  1e-08  3e-08
Optimal solution found.
[ 1.75e+00]
[-1.00e-09]
[ 4.00e+00]
[ 8.25e+00]
[ 3.50e+00]
[ 3.79e-09]



# Question 2 

## (A）

In [5]:
from cvxopt.glpk import ilp
import numpy as np
from cvxopt import matrix

In [4]:
d = np.matrix([[16.16,24.08,24.32,21.12], 
[19,26.47,27.24,17.33],
[25.29,32.49,33.42,12.25],
[0,7.93,8.31,36.12],
[3.07,6.44,7.56,37.37],
[1.22,7.51,8.19,36.29],
[2.8,10.31,10.95,33.5], 
[2.87,5.07,5.67,38.8], 
[3.8,8.01,7.41,38.16], 
[12.35,4.52,4.35,48.27], 
[11.11,3.48,2.97,47.14], 
[21.99,22.02,24.07,39.86], 
[8.82,3.3,5.36,43.31], 
[7.93,0,2.07,43.75], 
[9.34,2.25,1.11,45.43], 
[8.31,2.07,0,44.43], 
[7.31,2.44,1.11,43.43], 
[7.55,0.75,1.53,43.52],
[11.13,18.41,19.26,25.4], 
[17.49,23.44,24.76,23.21],
[11.03,18.93,19.28,25.43], 
[36.12,43.75,44.43,0]]).transpose()

In [6]:
w = np.array([[0.1609],
[0.1164],
[0.1026],
[0.1516],
[0.0939],
[0.132],
[0.0687],
[0.093],
[0.2116],
[0.2529],
[0.0868],
[0.0828],
[0.0975],
[0.8177],
[0.4115],
[0.3795],
[0.071],
[0.0427],
[0.1043],
[0.0997],
[0.1698],
[0.2531]])

In [7]:
c = d.flatten()
print(c)

[[16.16 19.   25.29  0.    3.07  1.22  2.8   2.87  3.8  12.35 11.11 21.99
   8.82  7.93  9.34  8.31  7.31  7.55 11.13 17.49 11.03 36.12 24.08 26.47
  32.49  7.93  6.44  7.51 10.31  5.07  8.01  4.52  3.48 22.02  3.3   0.
   2.25  2.07  2.44  0.75 18.41 23.44 18.93 43.75 24.32 27.24 33.42  8.31
   7.56  8.19 10.95  5.67  7.41  4.35  2.97 24.07  5.36  2.07  1.11  0.
   1.11  1.53 19.26 24.76 19.28 44.43 21.12 17.33 12.25 36.12 37.37 36.29
  33.5  38.8  38.16 48.27 47.14 39.86 43.31 43.75 45.43 44.43 43.43 43.52
  25.4  23.21 25.43  0.  ]]


In [8]:
list= np.zeros(shape=(22,88))

In [9]:
list

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [10]:
for i in range(22):
    for j in range(4):
        list[i,i + 22*j] = 1
        


In [11]:
A = list       

In [12]:
b =  np.ones(shape=(22,1))

In [13]:
b

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [14]:
w = w.reshape(1,-1)[0]

In [15]:
G = w.copy()

In [16]:
G= np.append(G,np.zeros(shape = (1,88)))

In [17]:
G= np.append(G,w)
G= np.append(G,np.zeros(shape = (1,88)))
G= np.append(G,w)
G= np.append(G,np.zeros(shape = (1,88)))
G= np.append(G,w)
G

array([0.1609, 0.1164, 0.1026, 0.1516, 0.0939, 0.132 , 0.0687, 0.093 ,
       0.2116, 0.2529, 0.0868, 0.0828, 0.0975, 0.8177, 0.4115, 0.3795,
       0.071 , 0.0427, 0.1043, 0.0997, 0.1698, 0.2531, 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.1609, 0.1164,
      

In [18]:
G.reshape(4,88)

array([[0.1609, 0.1164, 0.1026, 0.1516, 0.0939, 0.132 , 0.0687, 0.093 ,
        0.2116, 0.2529, 0.0868, 0.0828, 0.0975, 0.8177, 0.4115, 0.3795,
        0.071 , 0.0427, 0.1043, 0.0997, 0.1698, 0.2531, 0.    , 0.    ,
        0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
        0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
        0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
        0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
        0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
        0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
        0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
        0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
        0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
        0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.1609,

In [19]:
negG = -G

In [20]:
G = np.append(negG,G)

In [21]:
G.reshape(8,88)

array([[-0.1609, -0.1164, -0.1026, -0.1516, -0.0939, -0.132 , -0.0687,
        -0.093 , -0.2116, -0.2529, -0.0868, -0.0828, -0.0975, -0.8177,
        -0.4115, -0.3795, -0.071 , -0.0427, -0.1043, -0.0997, -0.1698,
        -0.2531, -0.    , -0.    , -0.    , -0.    , -0.    , -0.    ,
        -0.    , -0.    , -0.    , -0.    , -0.    , -0.    , -0.    ,
        -0.    , -0.    , -0.    , -0.    , -0.    , -0.    , -0.    ,
        -0.    , -0.    , -0.    , -0.    , -0.    , -0.    , -0.    ,
        -0.    , -0.    , -0.    , -0.    , -0.    , -0.    , -0.    ,
        -0.    , -0.    , -0.    , -0.    , -0.    , -0.    , -0.    ,
        -0.    , -0.    , -0.    , -0.    , -0.    , -0.    , -0.    ,
        -0.    , -0.    , -0.    , -0.    , -0.    , -0.    , -0.    ,
        -0.    , -0.    , -0.    , -0.    , -0.    , -0.    , -0.    ,
        -0.    , -0.    , -0.    , -0.    ],
       [-0.    , -0.    , -0.    , -0.    , -0.    , -0.    , -0.    ,
        -0.    , -0.    , -0.   

In [22]:
h1 = np.full((4,1),-0.8)

In [23]:
h2 = np.full((4,1),1.2)
h = np.append(h1,h2).reshape(8,1)

In [24]:
h

array([[-0.8],
       [-0.8],
       [-0.8],
       [-0.8],
       [ 1.2],
       [ 1.2],
       [ 1.2],
       [ 1.2]])

In [25]:
I=set(range(88))
B=set(range(88))

In [26]:
print(c.shape)
print(G.shape)
print(h.shape)
print(A.shape)
print(b.shape)

(1, 88)
(704,)
(8, 1)
(22, 88)
(22, 1)


In [27]:
(status,x)=ilp(matrix(c.transpose(),tc = 'd'), matrix(G.reshape(8,88),tc='d'), matrix(h,tc='d'),matrix(A,tc='d'), matrix(b,tc='d'),I,B) 

In [28]:
status

'optimal'

In [29]:
print(x)

[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 1.00e+00]
[ 1.00e+00]
[ 1.00e+00]
[ 1.00e+00]
[ 1.00e+00]
[ 1.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 1.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 1.00e+00]
[ 1.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 1.00e+00]
[ 0.00e+00]
[ 1.00e+00]
[ 1.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 1.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 1.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 1.00e+00]
[ 1.00e+00]
[ 1.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 1.00e+00]
[ 1.00e+00]
[ 1.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.

In [30]:
(np.array(x).reshape(4,22))

array([[0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0.,
        0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1.,
        1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 1.]])

we find that SR1 is assigned to hospitals
{4, 5, 6, 7, 8, 9, 12, 19, 20}, SR2 is assigned to hospitals {11, 13, 14, 18}, and SR3 is assigned to
hospitals {10, 15, 16, 17}, whereas SR4 is assigned to hospitals {1, 2, 3, 21, 22}.

## (D)

In [31]:
h1 = np.full((4,1),-0.9)
h2 = np.full((4,1),1.1)
h = np.append(h1,h2).reshape(8,1)

In [32]:
(status,x)=ilp(matrix(c.transpose(),tc = 'd'), matrix(G.reshape(8,88),tc='d'), matrix(h,tc='d'),matrix(A,tc='d'), matrix(b,tc='d'),I,B) 

In [33]:
status


'optimal'

In [34]:
(np.array(x).reshape(4,22))

array([[0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0.,
        1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1.,
        0., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 1., 1.]])

SR1 is assigned to hospitals {4, 5, 6, 7, 8, 9, 12, 19},

SR2 is assigned to hospitals {11, 13, 14, 18}, 

SR3 is assigned to hospitals {10, 15, 16, 18},

SR4 is assigned to hospitals {1, 2, 3, 20, 21, 22}.


# Question 3


In [35]:
a = 8/39.4

In [37]:
c1 = np.full((1,5),8/39.4)

In [39]:
c2 = np.full((1,5),8/117.4)

In [40]:
c3 = np.full((1,5),8/19.9)

In [41]:
c4 = np.full((1,5),8/26.3)

In [42]:
c5 = np.full((1,5),8/189.0)

In [49]:
c5

array([[0.04232804, 0.04232804, 0.04232804, 0.04232804, 0.04232804]])

In [47]:
c = np.concatenate((c1,c2,c3,c4,c5)).flatten()

In [48]:
c

array([0.20304569, 0.20304569, 0.20304569, 0.20304569, 0.20304569,
       0.0681431 , 0.0681431 , 0.0681431 , 0.0681431 , 0.0681431 ,
       0.40201005, 0.40201005, 0.40201005, 0.40201005, 0.40201005,
       0.30418251, 0.30418251, 0.30418251, 0.30418251, 0.30418251,
       0.04232804, 0.04232804, 0.04232804, 0.04232804, 0.04232804])

In [51]:
temp1 = np.array([[1,0,0,0,0]])

In [63]:
G1=np.concatenate((temp1,temp1,temp1,temp1,temp1)).flatten()

In [55]:
temp2 = np.array([[0,1,0,0,0]])
temp3 = np.array([[0,0,1,0,0]])
temp4 = np.array([[0,0,0,1,0]])
temp5 = np.array([[0,0,0,0,1]])

In [56]:
G2=np.concatenate((temp2,temp2,temp2,temp2,temp2)).flatten()
G3=np.concatenate((temp3,temp3,temp3,temp3,temp3)).flatten()
G4=np.concatenate((temp4,temp4,temp4,temp4,temp4)).flatten()
G5=np.concatenate((temp5,temp5,temp5,temp5,temp5)).flatten()

In [66]:
G11 = np.concatenate((G1,G2,G3,G4,G5)).reshape(5,25)

In [67]:
G11

array([[1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
        0, 0, 0],
       [0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
        0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        1, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 1]])

In [68]:
G21 = np.zeros(shape=(25,25))

In [70]:
for i in range(25):
    G21[i,i]=1

In [76]:
G31 = np.concatenate((np.ones(shape=(1,5)).flatten(),np.zeros(shape=(1,25)).flatten(),np.ones(shape=(1,5)).flatten(),np.zeros(shape=(1,25)).flatten(),np.ones(shape=(1,5)).flatten(),np.zeros(shape=(1,25)).flatten(),np.ones(shape=(1,5)).flatten(),np.zeros(shape=(1,25)).flatten(),np.ones(shape=(1,5)).flatten())).reshape(5,25)

In [77]:
G31

array([[1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 1., 1., 1., 1.]])

In [78]:
G = np.concatenate((G11,-G21,G21,-G31,G31))

In [80]:
G.shape

(65, 25)

In [81]:
h1 = np.full((5,1),10)

In [84]:
h2 = np.zeros((25,1))

In [85]:
h3 = np.array([2,2,2,2,2,3,3,3,3,3,0,1,0,1,0,1,1,1,1,1,6,6,6,6,6]).reshape(25,1)

In [86]:
h4 = np.array([-3,-12,-2,-2,-18,6,18,3,4,25]).reshape(10,1)

In [87]:
h = np.concatenate((h1,h2,h3,h4))

In [88]:
h.shape

(65, 1)

In [89]:
I=set(range(25))

In [90]:
(status,x)=ilp(-matrix(c.transpose(),tc = 'd'), matrix(G,tc='d'), matrix(h,tc='d'),matrix(1.,(0,25)),matrix(1.,(0,1)),I) 

In [91]:
status

'optimal'

In [93]:
(np.array(x).reshape(5,5))

array([[2., 2., 0., 0., 2.],
       [3., 3., 3., 3., 3.],
       [0., 1., 0., 1., 0.],
       [1., 1., 1., 1., 0.],
       [4., 3., 6., 5., 5.]])