In [29]:
#Import necessary Python packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

In [30]:
#Load the healthcare claim data
claim = pd.read_csv("ClaimsData.csv")
claim_data = np.array(claim)

In [31]:
claim.head()

age  alzheimers  arthritis  cancer  copd  depression  diabetes  \
0   85           0          0       0     0           0         0   
1   59           0          0       0     0           0         0   
2   67           0          0       0     0           0         0   
3   52           0          0       0     0           0         0   
4   67           0          0       0     0           0         0   

   heart.failure  ihd  kidney  osteoporosis  stroke  reimbursement2008  \
0              0    0       0             0       0                  0   
1              0    0       0             0       0                  0   
2              0    0       0             0       0                  0   
3              0    0       0             0       0                  0   
4              0    0       0             0       0                  0   

   bucket2008  reimbursement2009  bucket2009  
0           1                  0           1  
1           1                  0           1  
2           1                  0           1  
3           1                  0           1  
4           1                  0           1

In [32]:
print(claim_data.shape)

(458005, 16)


In [33]:
##For the covariates, we should remove the 2019 reimbursement amount information
X = claim_data[:,0:-2]
y = claim_data[:,-1]

In [34]:
print(X.shape)
print(y.shape)

(458005, 14)
(458005,)


In [35]:
## Split the data into training (75%) and testing (25%) data sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state= 88)

In [36]:
##Build the classification tree 
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn.metrics import accuracy_score

In [37]:
from sklearn.metrics import confusion_matrix
##Baseline model: Use the cost bucket of 2008 directly to predict the outcome of 2019
CM_baseline = confusion_matrix(y_test, X_test[:,13])
print(CM_baseline)
print(accuracy_score(y_test,  X_test[:,13]))

[[68887  4888  2073   919   121]
 [ 9930  6735  2936  1806   360]
 [ 4366  2861  1710  1061   212]
 [ 1719  1224   854   944   242]
 [  188   117   108   180    61]]
0.6841539885766188


In [38]:
#Input the penalty matrix
penalty = np.array([[0,1,2,3,4],[2,0,1,2,3],[4,2,0,1,2],[6,4,2,0,1],[8,6,4,2,0]])

In [39]:
print(penalty)

[[0 1 2 3 4]
 [2 0 1 2 3]
 [4 2 0 1 2]
 [6 4 2 0 1]
 [8 6 4 2 0]]


In [40]:
#Penalty Error for the baseline model
np.sum(np.multiply(CM_baseline,penalty))/np.sum(CM_baseline)

0.7387818553387714

In [44]:
#Build a classification tree to fit the trainin set. The maximum depth of the tree is set to be 4.
tree_D2Hawkeye = DecisionTreeClassifier(max_depth=5)

In [45]:
tree_D2Hawkeye.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=5,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [46]:
##Print out the tree
import graphviz
dot_data = export_graphviz(tree_D2Hawkeye,feature_names= ['age','alzheimers','arthritis','cancer','copd','depression','diabetes','heart.failure','ihd','kidney','osteoporosis','stroke','reimbursement2008','bucket2008'], class_names = ['1','2','3','4','5']) 
tree_graph = graphviz.Source(dot_data) 
tree_graph.render("D2Hawkeye") 


'D2Hawkeye.pdf'

In [19]:
#Make predictions on the testing data set
y_predict = tree_D2Hawkeye.predict(X_test)

In [20]:
#create the confusion matrix on the out-of-sample test
CM_tree = confusion_matrix(y_test, y_predict)
print(CM_tree)

[[72831  4057     0     0     0]
 [13017  8750     0     0     0]
 [ 5705  4505     0     0     0]
 [ 2234  2749     0     0     0]
 [  241   413     0     0     0]]


In [21]:
#The testing overall accuracy
print(accuracy_score(y_test, y_predict))

0.7124853714345601


In [22]:
#Penalty Error for the tree model
np.sum(np.multiply(CM_tree,penalty))/np.sum(CM_tree)

0.7923617054723935

In [47]:
#Cross-validated Parameter tuning for the maximum depth of the tree
from sklearn.model_selection import GridSearchCV
param_grid = {'max_depth':range(1, 7)}
grid = GridSearchCV(DecisionTreeClassifier(random_state=0),param_grid=param_grid,cv=10)
grid.fit(X_train, y_train)
print(grid.best_params_)
print('Best Overal Accuracy: %.2f' %grid.best_score_)

{'max_depth': 6}
Best Overal Accuracy: 0.71


In [48]:
## Fit a random-forest model with different numbers of trees (estimators) in the forest
from sklearn.ensemble import RandomForestClassifier

train_scores = []
test_scores = []

rf = RandomForestClassifier()
estimator_range = range(1, 100, 5)##Number of trees in the forest

for n_estimators in estimator_range:
    rf.n_estimators = n_estimators
    rf.fit(X_train, y_train)
    train_scores.append(rf.score(X_train, y_train))
    test_scores.append(rf.score(X_test, y_test))
    
print(train_scores)
print(test_scores)

[0.8448339606932108, 0.9275610402238117, 0.9511561762197128, 0.9573511730610795, 0.9615490985522688, 0.9630949365798843, 0.9640847387067945, 0.9645097713848205, 0.9650163171791803, 0.9651414980364073, 0.9653860373854086, 0.9654733728671947, 0.9655548859835286, 0.9656655109271244, 0.9656829780234816, 0.9656655109271244, 0.9657382904952795, 0.9657353793125533, 0.9657615799570891, 0.965758668774363]
[0.6307226074653718, 0.6625648460288903, 0.663324658084575, 0.6636215961293253, 0.6645648110950028, 0.664800614836422, 0.6656477616111509, 0.6657525632740039, 0.6647482140049955, 0.6647744144207088, 0.6652023545440254, 0.6651412202406944, 0.6663726397792178, 0.6657525632740039, 0.6665647761611151, 0.6664250406106443, 0.6660582347906587, 0.667018916700145, 0.6664512410263577, 0.6669839828125272]


In [23]:
## The importance of different features for a random forest of 100 trees

rf2=RandomForestClassifier(n_estimators=100).fit(X_train, y_train)
rf2.feature_importances_

array([0.28497675, 0.01491678, 0.01559512, 0.00896458, 0.01289003,
       0.01258243, 0.03047576, 0.02327335, 0.03098938, 0.01876693,
       0.01420838, 0.00879899, 0.46011042, 0.06345109])

In [49]:
#Load the boston housing data set and necessary models

from sklearn.datasets import load_boston
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler ##The scaling tool

boston = load_boston()
Xb = boston.data 
yb = boston.target
Xb_train, Xb_test, yb_train, yb_test = train_test_split(
    Xb, yb, random_state=0,test_size=0.25)

scaler = StandardScaler()
scaler.fit(Xb_train)

Xb_train_scaled = scaler.transform(Xb_train)
ridge = Ridge().fit(Xb_train_scaled, yb_train)

Xb_test_scaled = scaler.transform(Xb_test)


ridge.score(Xb_test_scaled, yb_test)

0.6345884564889053

In [50]:
#Combine transformation, model fit, and prediction together using pipeline
from sklearn.pipeline import make_pipeline
pipe = make_pipeline(StandardScaler(), Ridge())
pipe.fit(Xb_train, yb_train)
pipe.score(Xb_test, yb_test)

0.6345884564889053

In [26]:
#Pipeline meets grid-search cross validation to find the best number of neighbors for k-nearest neighbors regressor

from sklearn.neighbors import KNeighborsRegressor

knn_pipe = make_pipeline(StandardScaler(), KNeighborsRegressor())
param_grid = {'kneighborsregressor__n_neighbors': range(1, 10)}
grid = GridSearchCV(knn_pipe, param_grid, cv=10)
grid.fit(Xb_train, yb_train)
print(grid.best_params_)
print(grid.score(Xb_test, yb_test))


{'kneighborsregressor__n_neighbors': 7}
0.5999825126971097


/Users/rz26/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [52]:
##Include the polynomial features when fitting the model

from sklearn.preprocessing import PolynomialFeatures

poly_pipe = make_pipeline(PolynomialFeatures(degree=2), Ridge())

poly_pipe.fit(Xb_train_scaled, yb_train)
poly_pipe.score(Xb_test_scaled, yb_test)

0.6696430114132679

In [53]:
##Imbalancedness of the D2Hawkeye data set
print(np.bincount(y_train))
print(np.bincount(y_test))

[     0 230556  65332  30766  14860   1989]
[    0 76888 21767 10210  4983   654]


In [54]:
##Undersampling

from imblearn.under_sampling import RandomUnderSampler

rus = RandomUnderSampler(replacement=False)
X_train_subsample, y_train_subsample = rus.fit_sample(
    X_train, y_train)
print(X_train.shape)
print(X_train_subsample.shape)
print(np.bincount(y_train_subsample))

(343503, 14)
(9945, 14)
[   0 1989 1989 1989 1989 1989]


In [30]:
##Fit a CART model using the under sampled data
tree_D2Hawkeye.fit(X_train_subsample, y_train_subsample)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [31]:
#Examining the effect of undersampling 

y_predict = tree_D2Hawkeye.predict(X_test)
CM_tree_subsample = confusion_matrix(y_test, y_predict)
print(CM_tree_subsample)
print(accuracy_score(y_test, y_predict))

[[49015 21748  4346   777  1002]
 [ 2284 12050  4216   877  2340]
 [ 1182  5080  2085   428  1435]
 [  451  1971  1026   199  1336]
 [   43   212   110    21   268]]
0.5555972821435433


In [55]:
##Oversampling

from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler()
X_train_oversample, y_train_oversample = ros.fit_sample(X_train, y_train)
print(X_train.shape)
print(X_train_oversample.shape)
print(np.bincount(y_train_oversample))

(343503, 14)
(1152780, 14)
[     0 230556 230556 230556 230556 230556]


In [33]:
##Fit the decision tree model with the over-sampled data and examine its effectiveness on the testing data

tree_D2Hawkeye.fit(X_train_oversample, y_train_oversample)
y_predict = tree_D2Hawkeye.predict(X_test)
CM_tree_oversample = confusion_matrix(y_test, y_predict)
print(CM_tree_oversample)
print(accuracy_score(y_test, y_predict))

[[61304 11150  2720   262  1452]
 [ 5421  8980  4125   471  2770]
 [ 2599  3708  2028   253  1622]
 [ 1003  1439  1001   120  1420]
 [  103   156   106    11   278]]
0.6350107421704424


In [34]:
##SMOTE sampling method

from imblearn.over_sampling import SMOTE
smt = SMOTE()

##Standardize the covariates for the training and testing data
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_train_SMOTE, y_train_SMOTE = smt.fit_sample(X_train_scaled, y_train)
print(X_train_scaled.shape)
print(X_train_SMOTE.shape)
print(np.bincount(y_train_SMOTE))

/Users/rz26/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/Users/rz26/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/Users/rz26/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


(343503, 14)
(1152780, 14)
[     0 230556 230556 230556 230556 230556]


In [35]:
#Train the decision tree model on the training set with SMOTE and test it over the testing set
tree_D2Hawkeye.fit(X_train_SMOTE, y_train_SMOTE)
y_predict = tree_D2Hawkeye.predict(X_test_scaled)
CM_tree_SMOTE = confusion_matrix(y_test, y_predict)
print(CM_tree_SMOTE)
print(accuracy_score(y_test, y_predict))

[[56956 19256     0     0   676]
 [ 3918 16190     0     0  1659]
 [ 1956  7216     0     0  1038]
 [  732  3182     0     0  1069]
 [   78   351     0     0   225]]
0.6407835670992647
